base:
  test_size: 0.3
  random_state: 33


base_model:
  DecisionTree:
    max_depth: 4
    min_samples_leaf: 1

  AdaBoost:
    learning_rate: 0.01
    n_estimators: 100

  GradientBoosting:
    learning_rate: 0.01
    n_estimators: 200

  cross_validation: 5